<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    private const BUSINESS_ACCOUNT_INDEX = 'staff_members_business_account_unique';

    public function up(): void
    {
        Schema::create('staff_members', function (Blueprint $table): void {
            // Internal key for joins and indexes; never exposed by the API.
            $table->id();
            // Public identity, generated by IdGenerator before the row is written.
            $table->uuid('uuid')->unique();
            // Both relations point at the int primary key, which is what a new
            // table does here - the uuid columns on customers and users predate
            // that rule. The StaffMember entity still carries both neighbours'
            // uuids, so the repository adapter owns the uuid <-> int
            // translation and nothing above it ever sees these columns.
            //
            // Indexed explicitly: Postgres indexes neither side of a foreign
            // key for you, and each of these is at once a cascade target and a
            // hot lookup path - business_id lists a team, account_id resolves
            // the tenant on every authenticated request.
            $table->foreignId('business_id')->index()->constrained('businesses')->cascadeOnDelete();
            $table->foreignId('account_id')->index()->constrained('users')->cascadeOnDelete();
            // No role column. This table carries the membership fact alone -
            // this account may operate this business - and what the membership
            // may do is a Spatie role attached to the user, scoped to the
            // business through Spatie's team key. The one-owner-per-account
            // guarantee moved with it, to the partial unique index on
            // model_has_roles added in a later migration.
            $table->timestamps();
            $table->softDeletes();
        });

        // One membership per (business, account): a person holds a single
        // position at a business, so a second row would say nothing new.
        // Partial on deleted_at, so a membership that was given up does not bar
        // the same person from being taken on again.
        DB::statement(
            'create unique index '.self::BUSINESS_ACCOUNT_INDEX.
            ' on staff_members (business_id, account_id) where deleted_at is null'
        );
    }

    public function down(): void
    {
        DB::statement('drop index if exists '.self::BUSINESS_ACCOUNT_INDEX);

        Schema::dropIfExists('staff_members');
    }
};
