<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    private const OWNER_UNIQUE_INDEX = 'phones_owner_unique';

    private const COUNTRY_CODE_CHECK = 'phones_country_code_check';

    private const NATIONAL_NUMBER_CHECK = 'phones_national_number_check';

    public function up(): void
    {
        Schema::create('phones', function (Blueprint $table): void {
            // Internal key for joins and indexes; never exposed by the API.
            $table->id();
            // Public identity, generated by IdGenerator before the row is written.
            $table->uuid('uuid')->unique();
            // The morph alias of the owning domain - "business", "staff_member",
            // "customer" - and never an FQCN, which would not fit in 32 chars.
            // The aliases are the cases of PhoneOwnerType, registered by each
            // owning domain with Relation::enforceMorphMap.
            $table->string('phoneable_type', 32);
            // A uuid, and a deliberate exception to the project's int foreign key
            // rule. A morph column can carry no foreign key at all, so an int
            // would buy neither referential integrity nor a narrower join, and
            // would only force this domain's infrastructure to import three other
            // domains' models just to translate uuid -> int. The int rule earns
            // its keep where a real constraint exists; here there is none.
            $table->uuid('phoneable_id');
            $table->string('country_code', 2);
            $table->string('national_number', 15);
            $table->timestamps();
            $table->softDeletes();
            // The only lookup this table serves: the phone of a given owner.
            $table->index(['phoneable_type', 'phoneable_id'], 'phones_phoneable_index');
        });

        // The value objects already reject anything else, but the database is
        // what also holds seeders, console commands and manual fixes to it.
        DB::statement(
            'alter table phones add constraint '.self::COUNTRY_CODE_CHECK.
            " check (country_code in ('MX','US'))"
        );

        DB::statement(
            'alter table phones add constraint '.self::NATIONAL_NUMBER_CHECK.
            " check (national_number ~ '^[0-9]{7,15}$')"
        );

        // One phone per owner, enforced here rather than by a read-then-write in
        // the application, which two concurrent requests would lose. Partial, so
        // a soft deleted phone does not keep its owner from having a new one.
        DB::statement(
            'create unique index '.self::OWNER_UNIQUE_INDEX.
            ' on phones (phoneable_type, phoneable_id) where deleted_at is null'
        );
    }

    public function down(): void
    {
        DB::statement('drop index if exists '.self::OWNER_UNIQUE_INDEX);

        Schema::dropIfExists('phones');
    }
};
