<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    private const KEY_UNIQUE_INDEX = 'industries_key_unique';

    public function up(): void
    {
        Schema::create('industries', function (Blueprint $table): void {
            // Internal key for joins and indexes; never exposed by the API.
            $table->id();
            // Public identity, generated by IdGenerator before the row is written.
            $table->uuid('uuid')->unique();
            // The stable machine name of the catalog row. There is no label column:
            // labels are translations, and they live in the frontend's i18next
            // "industries" namespace keyed by this value.
            $table->string('key', 64);
            $table->unsignedSmallInteger('position')->default(0);
            // "active" is the business state and "deleted_at" is the record
            // lifecycle, and this table needs both: a retired industry has to keep
            // resolving for the businesses already pointing at it, so it is
            // deactivated - which hides it from the catalog - and never deleted.
            $table->boolean('active')->default(true);
            $table->timestamps();
            $table->softDeletes();
            // The one query this table serves: the active catalog, in order.
            $table->index(['active', 'position'], 'industries_catalog_index');
        });

        // Partial, so a soft deleted row does not keep its key reserved forever.
        DB::statement(
            'create unique index '.self::KEY_UNIQUE_INDEX.
            ' on industries ("key") where deleted_at is null'
        );
    }

    public function down(): void
    {
        DB::statement('drop index if exists '.self::KEY_UNIQUE_INDEX);

        Schema::dropIfExists('industries');
    }
};
