<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('customers', function (Blueprint $table): void {
            // Internal key for joins and indexes; never exposed by the API.
            $table->id();
            // Public identity, generated by IdGenerator before the row is written.
            $table->uuid('uuid')->unique();
            // Tenant discriminator: references businesses.uuid, not its int key.
            $table->uuid('business_id')->index();
            $table->foreign('business_id')->references('uuid')->on('businesses')->cascadeOnDelete();
            $table->string('name');
            $table->string('email')->nullable();
            $table->string('phone')->nullable();
            $table->timestamps();
            $table->softDeletes();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('customers');
    }
};
