<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    private const PROVIDER_USER_UNIQUE_INDEX = 'social_identities_provider_user_unique';

    public function up(): void
    {
        Schema::create('social_identities', function (Blueprint $table): void {
            // Internal key for joins and indexes; never exposed by the API.
            $table->id();
            // Public identity, generated by IdGenerator before the row is written.
            $table->uuid('uuid')->unique();
            // Relations point at the int primary key. The SocialIdentity entity
            // still carries the account uuid, so the repository adapter owns the
            // uuid <-> int translation and nothing above it ever sees this column.
            // Indexed explicitly: Postgres does not index a foreign key for you,
            // and this column is both the cascade target and how an account's
            // linked providers are listed.
            $table->foreignId('account_id')->index()->constrained('users')->cascadeOnDelete();
            $table->string('provider');
            $table->string('provider_user_id');
            $table->timestamps();
            $table->softDeletes();
        });

        // Partial, so an unlinked (soft deleted) identity does not block the same
        // Google account from ever being linked again. A plain unique index would.
        DB::statement(
            'create unique index '.self::PROVIDER_USER_UNIQUE_INDEX.
            ' on social_identities (provider, provider_user_id) where deleted_at is null'
        );
    }

    public function down(): void
    {
        DB::statement('drop index if exists '.self::PROVIDER_USER_UNIQUE_INDEX);

        Schema::dropIfExists('social_identities');
    }
};
